// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_or_create_keypair`, `save_message_to_db`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MoonlightBehaviourEvent`, `MoonlightBehaviour`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `handle_established_inbound_connection`, `handle_established_outbound_connection`, `handle_pending_inbound_connection`, `handle_pending_outbound_connection`, `on_connection_handler_event`, `on_swarm_event`, `poll`

void initLogger() => RustLib.instance.api.crateApiP2PInitLogger();

Future<void> initDb({required String path}) =>
    RustLib.instance.api.crateApiP2PInitDb(path: path);

Future<void> updateProfile({
  required String username,
  required String avatarBase64,
}) => RustLib.instance.api.crateApiP2PUpdateProfile(
  username: username,
  avatarBase64: avatarBase64,
);

Future<Profile> getProfile() => RustLib.instance.api.crateApiP2PGetProfile();

Future<List<P2pMessage>> getAllMessages() =>
    RustLib.instance.api.crateApiP2PGetAllMessages();

Stream<String> startNode() => RustLib.instance.api.crateApiP2PStartNode();

Future<void> broadcastMessage({required String content}) =>
    RustLib.instance.api.crateApiP2PBroadcastMessage(content: content);

class P2pMessage {
  final String peerId;
  final String username;
  final String avatarBase64;
  final String content;
  final PlatformInt64 timestamp;

  const P2pMessage({
    required this.peerId,
    required this.username,
    required this.avatarBase64,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      username.hashCode ^
      avatarBase64.hashCode ^
      content.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P2pMessage &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          username == other.username &&
          avatarBase64 == other.avatarBase64 &&
          content == other.content &&
          timestamp == other.timestamp;
}

class Profile {
  final String username;
  final String avatarBase64;

  const Profile({required this.username, required this.avatarBase64});

  @override
  int get hashCode => username.hashCode ^ avatarBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          avatarBase64 == other.avatarBase64;
}
